/// SHIP-01 compliance copy and entry URLs.
///
/// Hosted URLs are placeholders until live legal pages are published.
/// In-app document screens always show the full baseline text for App Review.
class ComplianceTexts {
  ComplianceTexts._();

  static const String privacyPolicyUrl = 'https://nocta.app/privacy';
  static const String termsOfServiceUrl = 'https://nocta.app/terms';

  static const String nonClinicalDisclaimer =
      'Nocta is a nighttime companionship and sleep-transition experience. '
      'It is not a medical device, not clinical care, not therapy, and not a '
      'crisis or emergency service. If you are in danger or need urgent help, '
      'contact local emergency services or a crisis hotline.';

  static const String llmCloudDisclosure =
      'When you chat with Nocta, your messages are sent over the internet to a '
      'cloud language-model provider so Nocta can generate a reply. Do not share '
      'information you are not comfortable sending to a third-party AI service.';

  static const String privacyPolicyBody = '''
Privacy Policy (V1 baseline)

Last updated: 2026-08-06

Nocta (“we”, “us”) provides a nighttime sleep-transition experience.

1. Information you provide
You may type messages during a night session. Those messages are processed to generate a reply and guide the sleep transition.

2. Cloud AI processing
Chat messages are transmitted to a third-party cloud language-model provider for response generation. That provider processes the content you send in order to return text to the app.

3. Purchases
If you subscribe or buy premium access, purchase status is handled through Apple and our payments partner (RevenueCat). We do not store your full payment card details in the app.

4. Device storage
The app may store local preferences on your device (for example, consent status) using on-device storage.

5. Not for medical or crisis use
Nocta is not a medical service and is not intended for diagnosis, treatment, or emergency support.

6. Contact
For privacy questions, contact: privacy@nocta.app

This in-app policy is the V1 baseline for App Store review. Replace hosted URL content when the public legal site is live.
''';

  static const String termsOfServiceBody = '''
Terms of Service (V1 baseline)

Last updated: 2026-08-06

By using Nocta you agree to these Terms.

1. The service
Nocta offers conversational nighttime companionship and audio sleep transition. Features may change as the product evolves.

2. Eligibility
You must be able to enter a binding agreement under the laws of your country. If you are under the age required by the App Store for this app’s age rating, do not use Nocta.

3. Acceptable use
Do not misuse the service, attempt to disrupt it, or use it for unlawful purposes.

4. AI-generated content
Replies may be generated by automated systems and can be imperfect. They are not professional advice.

5. Health & safety
Nocta is not medical care, therapy, or crisis support. Seek qualified help for medical or mental-health emergencies.

6. Subscriptions & purchases
Paid features are billed through Apple. Manage or cancel subscriptions in your Apple ID settings. Refunds follow Apple’s policies.

7. Disclaimer
The app is provided “as is” without warranties of uninterrupted or error-free operation to the fullest extent permitted by law.

8. Contact
support@nocta.app

This in-app Terms text is the V1 baseline for App Store review. Replace hosted URL content when the public legal site is live.
''';
}
